sorting stream
bharris47/niko-exercises pull request #5
Opened 2018-11-12 23:37 UTC by nikob411

2018-11-13 17:11 UTC, bharris47 requested changes
Give me a few sentences of what a heap is and why it's appropriate for this problem.

2018-11-13 17:11 UTC, bharris47 commented on exercises/sorting/sorted_stream.py
> +#             yield element
remove commented code

2018-11-13 17:14 UTC, nikob411 commented on exercises/sorting/sorted_stream.py
> +#             yield element
ARRRRRITE

2018-11-19 22:44 UTC, nikob411 commented on exercises/sorting/sorted_stream.py
> +#             yield element
Heap data structure is mainly used to represent a priority queue. We use heapify to convert the iterable into a heap data structure. We then use heapreplace to have the first element of the data popped then then pushed. The value larger than the pushed value can be returned. Lastly, we use heappop to sort the elements and maintain the heap structure.

2018-11-19 22:44 UTC, nikob411 commented on exercises/sorting/sorted_stream.py
> +#             yield element
Would like to see your solution.

2018-11-21 09:13 UTC, bharris47 approved these changes

2018-11-21 09:13 UTC, merged